Class('My.Template', {
    
    meta : 'Shotenjin.Joosed',
    
    template : {
        /*tj

            [%\
                var pos = 1
                
                Joose.O.each(stash, function (value, name) {
                    if (pos % 2) {
            %]
            
                        [% "name: [" + name + "], value: [" + value + "]" %]
            [%\
                    } else {
            %]
                        [% "value: [" + value + "], name: [" + name + "]" %]
            [%\
                    }
                    
                    pos++
                })
            %]
        
        tj*/

        /* GENERATED BY SHOTENJIN.JOOSED HELPER, DO NOT MODIFY DIRECTLY */
        sources : '[%\\nvar pos = 1\nJoose.O.each(stash, function (value, name) {\nif (pos % 2) {\n%]\n[% "name: [" + name + "], value: [" + value + "]" %]\n[%\\n} else {\n%]\n[% "value: [" + value + "], name: [" + name + "]" %]\n[%\\n}\npos++\n})\n%]'
    },

    
    methods : {
        
        customFunc : function (p1, p2) {
            return format(p1, p2, this.stash.p3)
        }
    }

})
