StartTest(function(t) {
    
    t.plan(2)
    
    var async0 = t.beginAsync()
    
    use('Shotenjin', function () {
        
        //======================================================================================================================================================================================================================================================
        t.diag('Sanity')
        
        t.ok(Shotenjin, "Shotenjin is here")
        
        
        //======================================================================================================================================================================================================================================================
        t.diag('Template with capturing')

        Template('Test', {
            
            template : {
                /*tj
                    [%\
                        var fragment = this.capture(function () {
                            for (var i = 1; i <= 5; i++) this.echo(i + ';')
                        })
                    %]
                        
                    Fragment1: [% fragment %]
                    Fragment2: [% fragment %]
                tj*/

                /* GENERATED BY SHOTENJIN.JOOSED HELPER, DO NOT MODIFY DIRECTLY */
                sources : '[%\\\nvar fragment = this.capture(function () {\nfor (var i = 1; i <= 5; i++) this.echo(i + \';\')\n})\n%]\nFragment1: [% fragment %]\nFragment2: [% fragment %]'
            }
        
        
        })

        //======================================================================================================================================================================================================================================================
        t.diag('Rendering')
        
        t.ok(Test() == 'Fragment1: 1;2;3;4;5;\nFragment2: 1;2;3;4;5;', 'Capturing works correctly')

        t.endAsync(async0)
    })
})    
