StartTest(function(t) {
    
    t.plan(2)
    
    var async0 = t.beginAsync()
    
    use('Shotenjin.Joosed', function () {
        
        //======================================================================================================================================================================================================================================================
        t.diag('Sanity')
        
        t.ok(Shotenjin.Joosed, "Shotenjin.Joosed is here")
        
        
        //======================================================================================================================================================================================================================================================
        t.diag('Template with wrapping')

        Template('Chapter', {
            
            template : {
                /*tj
                    <h2>[% title %]</h2>
                    <p> [% content %]</p>
                tj*/

                /* GENERATED BY SHOTENJIN.JOOSED HELPER, DO NOT MODIFY DIRECTLY */
                sources : '<h2>[% title %]</h2>\n<p> [% content %]</p>'
            }
        })
        
        
        Template('Book', {
            
            template : {
                /*tj
                    [%\ this.wrap(Chapter, { title : 'Chapter1' }, function () { %]                     
                        Text of first chapter.
                    [%\ }); %]

                    [%\ this.wrap(Chapter, { title : 'Chapter2' }, function () { %]
                        Text of second chapter.
                    [%\ }) %]
                tj*/

                /* GENERATED BY SHOTENJIN.JOOSED HELPER, DO NOT MODIFY DIRECTLY */
                sources : '[%\\ this.wrap(Chapter, { title : \'Chapter1\' }, function () { %]                     \nText of first chapter.\n[%\\ }); %][%\\ this.wrap(Chapter, { title : \'Chapter2\' }, function () { %]\nText of second chapter.\n[%\\ }) %]'
            }
        })

        //======================================================================================================================================================================================================================================================
        t.diag('Rendering')
        
        t.ok(Book() == '<h2>Chapter1</h2>\n<p> Text of first chapter.\n</p><h2>Chapter2</h2>\n<p> Text of second chapter.\n</p>', 'Wrapping works correctly')

        t.endAsync(async0)
    })
})    


